/*	SCCS Id: @(#)date.h	3.4	2002/02/03 */

/* This source file is generated by 'makedefs'.  Do not edit. */
#define BUILD_DATE "Sun Jan 01 03:20:21 2017"
#define BUILD_TIME (1483269621L)

#define VERSION_NUMBER 0x00000707UL
#define VERSION_FEATURES 0x181fee4cUL
#define IGNORED_FEATURES 0x00800000UL
#define VERSION_SANITY1 0x4b23e2a0UL
#define VERSION_SANITY2 0xac99d600UL

#define VERSION_STRING "0.0.7E7F3"
#define VERSION_ID \
 "Windows SlashTNG tty Version 0.0.7E7F3 - last build Sun Jan 01 03:20:21 2017."
